### PR TITLE
Prepare statements and reuse

### PR DESCRIPTION
**Pull request by JinyangLi01**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3)

### CODE REVIEW

**Comment by MinhyukPark** [comment]
so the query statements and the way we are integrating them seem perfectly good to me. Should we merge this and start the work of transitioning backend calls to use the proper prepare statements then? or do you have more changes coming

**Review by MinhyukPark — CHANGES_REQUESTED** [review]
Why are the toplevel functions called Execute[action] like execute insert row? and where is the PrepareQueryMulStmt function?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-:-M3JIfdP54Dl37wUusHu:b49tggj)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lijinyang0228 and @MinhyukPark)

___
*[mysqlint.go, line 144 at r2](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-M3JKNtT62HdlREZnFPh:-M3JKNtT62HdlREZnFPi:bvk8jeu) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/a379847377416ccfe6059ad32c73233f5f374043/mysqlint.go#L144)):*
> ```Go
> }
> 
> func mysqlExecureQueryMulStmt(QueryMulStmt *sql.Stmt, QueryIDs []interface{}) (*sql.Rows, error) {
> ```

typo Execure -> Execute

**Review by MinhyukPark — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3)* status: all files reviewed, 1 unresolved discussion (waiting on @lijinyang0228)

**Comment by JinyangLi01** [comment]
Because these functions are used to execute a sql statement. What do you think I should call them? PrepareQueryMulStmt function is in sqlinterface.go

**Comment by JinyangLi01** [comment]
___
*[mysqlint.go, line 144 at r2](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-M3JKNtT62HdlREZnFPh:-M3J_xVk1e2RXNbdXXBu:b-t7ytr9) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/a379847377416ccfe6059ad32c73233f5f374043/mysqlint.go#L144)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

typo Execure -> Execute
</blockquote></details>

have fixed it in the next PR

**Review by MinhyukPark — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by MinhyukPark — APPROVED** [review]
Looks good to me. We should merge this in once the backend catches up and it won't break the functionalities.

> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-:-M3Yb4ZdD5mxv0_dDd6O:b-ku8f67)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JinyangLi01** [comment]
___
*[mysqlint.go, line 571 at r4](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-M3o9agoAOk4BqyLViZi:-M3o9agoAOk4BqyLViZj:b95enxl) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/170ac37ce7d9c13b1f0c80d4d684843cdbff30b5/mysqlint.go#L571)):*
> ```Go
> 
> 
> func mysqlInsertRow(indexCol string, cells []Cell, maxIndex int, InsertOneStmt *sql.Stmt, exists bool) int {
> ```

In this function we need to check whether a value in cells is null, otherwise, null will become 0 when we update a row.

**Review by MinhyukPark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lijinyang0228 and @MinhyukPark)

___
*[mysqlint.go, line 571 at r4](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-M3o9agoAOk4BqyLViZi:-M42GhZ--XqB_fqAOOS8:b2nign6) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/170ac37ce7d9c13b1f0c80d4d684843cdbff30b5/mysqlint.go#L571)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

In this function we need to check whether a value in cells is null, otherwise, null will become 0 when we update a row.
</blockquote></details>

yes

**Review by MinhyukPark — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/3#-:-M42Gqs20OwdBjSICllL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lijinyang0228)

**Comment by JinyangLi01** [comment]
do you think we can merge it into master?

**Pull request merged**
