### PR TITLE
Add GetColumns

### PR DESCRIPTION
**Pull request by JinyangLi01**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/1)

### CODE REVIEW

**Comment by MinhyukPark** [comment]
___
*[common.go, line 31 at r1](https://reviewable.io/reviews/minhyukpark/go-sql-interface/1#-LxA3ag210swwVF6OSza:-LxA3ag210swwVF6OSzb:b3y9rhh) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/b5d71be6c08bf319dfd0e2edd88946f196aa426c/common.go#L31)):*
> ```Go
> // ColumnAccess : struct to request columns from the database
> type ColumnAccess struct {
>     Attributes []string
> ```

So is it ok if we rename this to something like ColumnNames? I was initially confused as to what Attributes meant.

**Comment by MinhyukPark** [comment]
self assigning +@minhyukpark

**Comment by JinyangLi01** [comment]
___
*[common.go, line 31 at r1](https://reviewable.io/reviews/minhyukpark/go-sql-interface/1#-LxA3ag210swwVF6OSza:-LxA4gOf7U1Y3D4oqU7f:bb7f2mf) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/b5d71be6c08bf319dfd0e2edd88946f196aa426c/common.go#L31)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

So is it ok if we rename this to something like ColumnNames? I was initially confused as to what Attributes meant.
</blockquote></details>

done

**Comment by MinhyukPark** [comment]
Go ahead and merge it as long as there are no errors.
:lgtm:

**Review by MinhyukPark — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JinyangLi01** [comment]
merge to master?

**Comment by MinhyukPark** [comment]
If you look on the top right, there should be a green button that says merge and retain branch. Click on the arrow pointing down, click sqash and merge for the style and then delete for the branch. After this the green button should turn into squash and delete branch. Hold the button and then let it go to merge.

**Comment by JinyangLi01** [comment]
Am I doing the right thing?

**Comment by MinhyukPark** [comment]
Yep. Looks perfect to me.

**Pull request merged**
