### PR TITLE
Adds delete column endpoint

### PR DESCRIPTION
**Pull request by MinhyukPark**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/4)

### CODE REVIEW

**Review by MinhyukPark — COMMENTED** [review]
+@lijinyang0228 
+@apappu9 
+@laurenho025 

Adds the delete column endpoint but nothing else is special about it. Haven't tested fully with the frontend since i don't have a component that calls the new endpoint yet in the frontend.

> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/4#-:-M4lgFc4-JRmgkiM97ba:b-r0beih)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @apappu9, @laurenho025, and @lijinyang0228)

**Comment by JinyangLi01** [comment]
:lgtm:

**Review by abhinavpappu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/4#-:-M4uq4nZ-S0TVjRm956S:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @apappu9, @laurenho025, and @lijinyang0228)

**Review by laurenho025 — APPROVED** [review]

**Review by abhinavpappu — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @laurenho025 and @lijinyang0228)

**Pull request merged**
