### PR TITLE
fix insert column function, change insert row function for null vs null

### PR DESCRIPTION
**Pull request by JinyangLi01**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5)

### CODE REVIEW

**Review by MinhyukPark — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-:-M4p9ihbAVOJO7t0aRwf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lijinyang0228)

___
*[mysqlint.go, line 556 at r1](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-M4p9XyjEo7KAPgFnGrZ:-M4p9XyjEo7KAPgFnGr_:b-jrxcue) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/4ab03b3d18a8e648a9accf1c2aa95f2a98fa7209/mysqlint.go#L556)):*
> ```Go
> 
> func mysqlInsertRow(cells []interface{}, maxIndex int, InsertOneStmt *sql.Stmt, exists bool) int {
>     fmt.Println("Here is mysqlInsertRow")
> ```

comment
___
*[mysqlint.go, line 557 at r1](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-M4p9a9GBp_mFDaiaRPq:-M4p9a9GBp_mFDaiaRPr:b-d7f4md) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/4ab03b3d18a8e648a9accf1c2aa95f2a98fa7209/mysqlint.go#L557)):*
> ```Go
> func mysqlInsertRow(cells []interface{}, maxIndex int, InsertOneStmt *sql.Stmt, exists bool) int {
>     fmt.Println("Here is mysqlInsertRow")
>     /*
> ```

should get rid of the next few commented out cells

**Comment by JinyangLi01** [comment]
___
*[mysqlint.go, line 556 at r1](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-M4p9XyjEo7KAPgFnGrZ:-M4qs-Vj4Y3y7PUefRbE:b-9unw5o) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/4ab03b3d18a8e648a9accf1c2aa95f2a98fa7209/mysqlint.go#L556)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

comment
</blockquote></details>

deleted

**Comment by JinyangLi01** [comment]
___
*[mysqlint.go, line 557 at r1](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-M4p9a9GBp_mFDaiaRPq:-M4qs1Pp0Eb8zAWmfqdM:b-9unw5o) ([raw file](https://github.com/minhyukpark/go-sql-interface/blob/4ab03b3d18a8e648a9accf1c2aa95f2a98fa7209/mysqlint.go#L557)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

should get rid of the next few commented out cells
</blockquote></details>

deleted

**Review by MinhyukPark — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by MinhyukPark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-:-M4u7q7O10s4Fvxk_wlD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JinyangLi01** [comment]
Insert column function is good now.
But I also change insert row function which is still under discussion

**Review by JinyangLi01 — COMMENTED** [review]
only Insert Column is changed if you compare the latest version with the original one

> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5#-:-M5byqOH1l4aNaR3Ny_9:bz7d959)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MinhyukPark)

**Review by MinhyukPark — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by MinhyukPark — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/minhyukpark/go-sql-interface/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
